name: clrn prod

on:
  push:
    branches:
      - master
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Create .env
      run: cp /projects/teachers-runner/_config/.env ./.env
    - name: Create volumes
      run: |
        docker volume create tb_db_data
        docker volume create tb_redis_data
        docker volume create tb_media
    - name: Fix docker-compose.yml
      run: |
        rm ./docker-compose.yml
        cp /projects/teachers-runner/_config/docker-compose.yml ./docker-compose.yml
    - name: Make upb
      run: make upb
